### ISSUE TITLE
Error on log function

### ISSUE THREAD

**Issue by henrikopersson** [CaseyLabs/aws-ec2-ebs-automatic-snapshot-powershell#2]
Getting error when running file 3-ebs-snapshot.ps1 on the log function

At C:\AWS\3-ebs-snapshot.ps1:101 char:105
- ... Event ID 1377)."
-                    ~
  The string is missing the terminator: ".
  At C:\AWS\3-ebs-snapshot.ps1:37 char:22
- function log ($type) {
-                      ~
  Missing closing '}' in statement block.
  - CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
  - FullyQualifiedErrorId : TerminatorExpectedAtEndOfString

**Comment by Rcjuk** [comment]
I get the same.

**Comment by CaseyLabs** [comment]
Hi all,

It looks like there was a minor character encoding issue. I've updated the scripts... could you please download the latest version and try again?

Thanks!

**Comment by henrikopersson** [comment]
Thanks, seems to work now.

**Comment by Rcjuk** [comment]
Looks good to me.
